name: Java Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK (Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven build (compile and package)
      - name: Build with Maven
        run: mvn clean package

      # Run Maven tests
      - name: Run tests with Maven
        run: mvn test

      # Upload JAR as an artifact (optional)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-jar
          path: target/*.jar

